### ISSUE TITLE
Mapa Act1 Kevin Osorio 1 "BS"

### ISSUE THREAD

**Issue by KevinOsorio23143** [SistemasTecTlaxiaco/actividad-4-mapa-mental-KevinOsorio23143#1]
[Mapa mental Kevin Osorio.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-KevinOsorio23143/files/9603844/Mapa.mental.Kevin.Osorio.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
De la actividad 4
Obtuviste un 17.8% del 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
